[tools]
"aqua:fish-shell/fish-shell" = "latest"
croc = "latest"
neovim = "latest"
lazygit = "latest"
aws-vault = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
node = "lts/krypton"
pnpm = "latest"
bun = "latest"
dotenvx = "latest"
opencode = "latest"
"npm:ocx" = "latest"


[settings]
experimental = true
lockfile = true

[shell_alias]
ms = "./bin/mise"

[tasks.omo-setup]
run = '''
  bunx oh-my-opencode-slim install --no-tui '--skills=yes' '--tmux=no' \
    '--opencode-free=yes' '--opencode-free-model=auto' \
    '--kimi=no' '--openai=no' '--anthropic=no' '--copilot=no' \
    '--zai-plan=no' '--antigravity=no' '--chutes=no' 
'''
